Rails/Advanced Rails Forms/RedditClone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:create, :destroy, :new]
  resources :subs, only: [:index, :show, :new, :create, :edit, :update]
  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get "new_comment"
      post "upvote"
      post "downvote"
    end
  end

  resources :comments, only: [:create, :destroy]

  root to: redirect("/posts")
end

Rails/Advanced Rails Forms/RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :integer          not null
#
class Post < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :author_id, presence: true

  belongs_to(:author, {
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User
  })

  has_many(:post_subs, {
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :PostSub
  })

  has_many(
    :subs,
    through: :post_subs,
    source: :sub
  )

  has_many(:comments, {
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Comment
  })
end

Rails/Advanced Rails Forms/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_current_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.all.order(updated_at: :desc)
    @subs = Sub.all.order(created_at: :desc)
    @post_and_votes = {}
    @posts.each do |post|
      @post_and_votes[post] = Vote.where({post_id: post.id}).first
    end
    render :index
  end

  def new_comment
    @post = Post.find_by({id: params[:id]})
    render :new_comment
  end

  def upvote
    @vote = Vote.find_by({post_id: params[:id]})
    if @vote == nil
      new_vote = Vote.new({post_id: params[:id]})
      new_vote.upvote
    else
      @vote.upvote
    end
    redirect_to posts_url
  end

  def downvote
    @vote = Vote.find_by({post_id: params[:id]})
    if @vote == nil
      new_vote = Vote.new({post_id: params[:id]})
      new_vote.downvote
    else
      @vote.downvote
    end
    redirect_to posts_url
  end

  def new
    @subs = Sub.all
    render :new
  end

  def show
    @post = Post.find_by({id: params[:id]})
    @post_and_votes = {}
    @post_and_votes[@post] = Vote.where({post_id: @post.id}).first
    render :show
  end

  def edit
    @subs = Sub.all
    @post = Post.find_by({id: params[:id]})
    if current_user == @post.author
      render :edit
    else
      not_your_post_process(@post)
    end
  end

  def create
    params_to_pass = post_params
    params_to_pass[:author_id] = current_user.id
    @post = Post.new(params_to_pass)
    if @post.save
      params[:post][:sub_ids].each do |sub_id|
        PostSub.create({sub_id: sub_id.to_i, post_id: @post.id })
      end
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to new_post_url
    end
  end

  def update
    @post = Post.find_by({id: params[:id]})
    if current_user == @post.author
      if @post.update(post_params)
        redirect_to post_url(@post)
      else
        flash[:errors] = @post.errors.full_messages
        redirect_to edit_post_url(@sub)
      end
    else
      not_your_post_process(@post)
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.destroy!
      redirect_to posts_url
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to post_url(@post)
    end
  end


  def not_your_post_process(post)
    flash[:errors] = ["This is not your post to edit"]
    redirect_to post_url(post)
  end

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end
end

Rails/Advanced Rails Forms/RedditClone/app/views/posts/edit.html.erb
<h2>Edit post</h2>

<div class="form-box">
  <form action="<%= post_url(@post.id) %>" method="POST">
    <input type="hidden" name="_method" value="PUT">
    <%= auth_token %>
    <div class="flex-column">
      <label for="post_title">Title</label>
      <input type="text" name="post[title]" id="post_title" value="<%= @post.title %>">
    </div>
    <div class="flex-column">
      <label for="post_url">Url</label>
      <input type="text" name="post[url]" id="post_url" value="<%= @post.url %>">
    </div>
   <div class="flex-column">
      <label for="post_content">Content</label>
      <textarea name="post[content]" id="post_content"><%= @post.content %></textarea>
    </div>
    <input class="button" type="submit" value="Update Post">
  </form>
</div>

Rails/Advanced Rails Forms/RedditClone/app/views/posts/index.html.erb
<h5 class="big-title">Popular Posts</h5>

<div class="col col-2-3">
  <ul class="posts">
    <% @posts.each do |post| %>
      <li class="cf">
          <div class="flex-column voting">
            <div class="vote-count"><%= @post_and_votes[post] == nil ? "0" : @post_and_votes[post].value %></div>
            <div>
              <form class="inline-block" action="<%= upvote_post_url(post.id) %>" method="POST">
                <%= auth_token %>
                <input class="button bg-blue inline-block" type="submit" value="&#xf0aa;" />
              </form>
            </div>
            <div>
              <form class="inline-block" action="<%= downvote_post_url(post.id) %>" method="POST">
                <%= auth_token %>
                <input class="button bg-red inline-block" type="submit" value="&#xf0ab;" />
              </form>
            </div>
          </div>
          <div class="cf">
            <figure class="author"><%= post.author.email %> wrote <figure class="date"><%= post.updated_at.strftime("%a %H:%M")%></figure></figure>
            <a class="post-title" href="<%= post_url(post.id) %>"><%= post.title %></a>
            <figure class="posted-in-forums">
              Posted in:
              <% post.subs.each_with_index do |sub, index| %>
                <a class="sub-url" href="<%= sub_url(sub) %>"><%= sub.title %></a><%= index != post.subs.length-1 ? "," : nil %>
              <% end %>
            </figure>
          </div>
        </a>
      </li>
    <% end %>
  </ul>
</div>
<div class="col col-1-3">
  <ul class="index subs">
    <h5 class="small-title">Popular Sub-Forums</h5>
    <% @subs.each do |sub| %>
      <li><a href="<%= sub_url(sub.id) %>"><%= sub.title %> </a></li>
    <% end %>
  </ul>
</div>

Rails/Advanced Rails Forms/RedditClone/app/views/posts/new.html.erb
<h5 class="big-title">New Post</h5>
<div class="form-box">
  <form action="<%= posts_url %>" method="POST">
    <%= auth_token %>
    <div>
      <p>Subs to post to:</p>
      <% @subs.each do |sub| %>
        <label>
          <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>">
          <%= sub.title %>
        </label>
      <% end %>

    </div>
    <div class="flex-column">
      <label for="post_title">Title</label>
      <input type="text" name="post[title]" id="post_title">
    </div>
    <div class="flex-column">
      <label for="post_url">Url</label>
      <input type="text" name="post[url]" id="post_url">
    </div>
   <div class="flex-column">
      <label for="post_content">Content</label>
      <textarea name="post[content]" id="post_content"></textarea>
    </div>
    <input class="button" type="submit" value="Create Post">
  </form>
</div>

Rails/Advanced Rails Forms/RedditClone/app/views/posts/new_comment.html.erb
<h2 class="big-title">New Comment on "<%= @post.title %>"</h2>

<div class="form-box">
  <form action="<%= comments_url %>" method="POST">
    <%= auth_token %>
    <div class="flex-column">
      <label for="comment_post_id">Post to comment on</label>
      <select id="comment_post_id" name="comment[post_id]">
        <option disabled>--- Post to comment on ---</option>
          <option selected value="<%= @post.id %>"><%= @post.title %></option>
      </select>
    </div>
    <div class="flex-column">
      <label for="comment_body">Body</label>
      <textarea name="comment[body]" id="comment_body"></textarea>
    </div>
    <input class="button" type="submit" value="Create Post">
  </form>
</div>

Rails/Advanced Rails Forms/RedditClone/app/views/posts/show.html.erb
<h2 class="big-title"><%= @post.title %></h2>
<div class="form-box post">
  <div class="flex-column voting">
    <div class="vote-count"><%= @post_and_votes[@post] == nil ? "0" : @post_and_votes[@post].value %></div>
    <div>
      <form class="inline-block" action="<%= upvote_post_url(@post.id) %>" method="POST">
        <%= auth_token %>
        <input class="button bg-blue inline-block" type="submit" value="&#xf0aa;" />
      </form>
    </div>
    <div>
      <form class="inline-block" action="<%= downvote_post_url(@post.id) %>" method="POST">
        <%= auth_token %>
        <input class="button bg-red inline-block" type="submit" value="&#xf0ab;" />
      </form>
    </div>
  </div>
  <figure class="author"><%= @post.author.email %> wrote <figure class="date"><%= @post.updated_at.strftime("%a %H:%M")%></figure></figure>
  <section class="fr">
    <% @post.subs.each_with_index do |sub, index| %>
      <a class="sub-url" href="<%= sub_url(sub) %>"><%= sub.title %></a><%= index != @post.subs.length-1 ? "," : nil %>
    <% end %>
  </section>
  <section class="post-link">
    <a class="link" href="<%= @post.url %>"><%= @post.url%> </a>
  </section>
  <article><%= @post.content %></article>


  <div class="below-comments">
    <% if logged_in?%>
      <a class="button inline-block" href="<%= new_comment_post_url(@post.id) %>">Comment</a>
    <% end %>
  <% if @post.author == current_user %>
    <a class="button inline-block" href="<%= edit_post_url(@post) %>">Edit your post</a>
    <form class="inline-block" action="<%= post_url(@post.id) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <%= auth_token %>
      <input type="hidden" value="delete" name="_method" />
      <input class="button bg-red inline-block" type="submit" value="Delete post" />
    </form>
  <% end %>
  </div>
</div>


  <ul class="comments">
    <% @post.comments.each do |comment| %>
    <li class="comments form-box" style="margin-top:10px;">
      <figure class="author"><%= comment.author.email %> wrote <figure class="date"><%= comment.updated_at.strftime("%a %H:%M")%></figure></figure>
      <article><%= comment.body %></article>
      </li>
    <% end %>
  </ul>
</div>