Rails/Advanced Rails Forms/RedditClone/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:create, :destroy, :new]
  resources :subs, only: [:index, :show, :new, :create, :edit, :update]
  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get "new_comment"
      post "upvote"
      post "downvote"
    end
  end

  resources :comments, only: [:create, :destroy]

  root to: redirect("/posts")
end

Rails/Advanced Rails Forms/RedditClone/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul class="errors">
  <% flash[:errors].each do |error| %>
    <li>&#x26A0;&nbsp;&nbsp;<%= error %></li>
  <% end %>
  </ul>
<% end %>

Rails/Advanced Rails Forms/RedditClone/app/views/shared/_nav.html.erb
<nav>
  <ul class="logo-list">
    <li><img class="logo-img" src="/assets/logo.jpg"></li>
    <li><a href="<%= posts_url %>">RedditClone</a></li>
  </ul>
  <ul class="buttons">
    <% if logged_in? %>
      <li><a href="<%= posts_url %>">All Posts</a></li>
      <li><a href="<%= new_sub_url %>">New sub</a></li>
      <li><a href="<%= new_post_url %>">New post</a></li>
      <li><a href="<%= user_url(current_user) %>">Profile</a></li>
      <li>
        <form class="inline-block" action="<%= session_url %>" method="POST">
          <%= auth_token %>
          <input type="hidden" value="delete" name="_method" />
          <input class="button logout" type="submit" value="Logout" />
        </form>
      </li>
    <% else %>
      <li><a href="<%= posts_url %>">All Posts</a></li>
      <li><a href="<%= new_session_url %>">Login</a></li>
      <li><a href="<%= new_user_url %>">Signup</a></li>
    <% end %>
  </ul>
</nav>