Rails/Testing with Rails/SocialGoalsApp/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :destroy, :new]
  resources :user_comments, only: [:create, :destroy]
  resources :goal_comments, only: [:create, :destroy]

  resources :users, only: [:new, :create, :show] do
    member do
      get "user_comment"
    end
  end

  resources :goals, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get "goal_comment"
    end
  end

  root to: redirect("/goals")
end

Rails/Testing with Rails/SocialGoalsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialGoalsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="nav cb">
      <% if logged_in? %>
        <form class="fr" class="logout" action="<%= session_url %>" method="POST">
        <input type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
        <input type="hidden" value="delete" name="_method" />
        <input class="logout-btn" type="submit" value="Logout" />
      </form>
      <a class="fr mr" href="<%= user_url(current_user) %>">My Profile</a>
    <% else %>
      <a class="fr" href="<%= new_session_url %>">Login</a>
      <a class="fr mr" href="<%= new_user_url %>">Signup</a>
    <% end %>
      <a href="<%= goals_url %>">Goals Board</a>
  </div>
    <div class="wrap">
      <%= yield %>
    </div>
  </body>
</html>