Rails/Testing with Rails/SocialGoalsApp/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:create, :destroy, :new]
  resources :user_comments, only: [:create, :destroy]
  resources :goal_comments, only: [:create, :destroy]

  resources :users, only: [:new, :create, :show] do
    member do
      get "user_comment"
    end
  end

  resources :goals, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      get "goal_comment"
    end
  end

  root to: redirect("/goals")
end

Rails/Testing with Rails/SocialGoalsApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  email            :string           not null
#  password_digest  :string           not null
#  session_token    :string           not null
#  activated        :boolean          default(FALSE), not null
#  activation_token :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class User < ApplicationRecord
  attr_reader :password

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: { message: 'Password can\'t be blank' }
  validates :session_token, presence: true
  validates :activation_token, presence: true
  validates :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token
  after_initialize :ensure_activation_token

  has_many(:authored_user_comments, {
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :UserComment,
    dependent: :destroy
  })

  has_many(:authored_goal_comments, {
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :GoalComment,
    dependent: :destroy
  })

  has_many(:user_comments, {
    primary_key: :id,
    foreign_key: :for_user_id,
    class_name: :UserComment,
    dependent: :destroy
  })

  def self.find_by_credentials(email, password)
    user_check = User.find_by({email: email})
    return nil if user_check == nil
    return user_check if user_check.is_password?(password)
    return false
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.generate_activation_token
    SecureRandom::urlsafe_base64(32)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def ensure_activation_token
    self.activation_token ||= User.generate_activation_token
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def set_activated!
    self.activated = true
    self.save
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end
end

Rails/Testing with Rails/SocialGoalsApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def user_comment
    @users = User.all
    render :new_user_comment
  end

  def show
    @user = User.find_by({id: params[:id]})
    @user_comments = UserComment.where({for_user_id: params[:id]})
    if logged_in?
      if params[:id].to_i == current_user.id.to_i
        @goals = Goal.where({user_id: params[:id]})
      else
        @goals = Goal.where({user_id: params[:id], is_public: true})
      end
    else
      @goals = Goal.where({user_id: params[:id], is_public: true})
    end
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user.email, @user.password)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

Rails/Testing with Rails/SocialGoalsApp/app/views/users/new.html.erb
<h2>New User</h2>

<%= render 'shared/errors' %>

<form action="<%= users_url %>" method="POST">
  <%= auth_token %>

  <div class="mt">
    <label for="user_email">Email</label><br>
    <input class="mt" type="text" name="user[email]" id="user_email">
  </div>

  <div class="mt">
    <label for="user_password">Password</label><br>
    <input class="mt" type="password" name="user[password]" id="user_password">
  </div>

  <input class="btn font-em mt" type="submit" value="Sign up">
</form>

Rails/Testing with Rails/SocialGoalsApp/app/views/users/new_user_comment.erb
<h2>New comment on user</h2>
<%= render 'shared/errors' %>

<form class="mb" action="<%= user_comments_url %>" method="POST">
  <%= auth_token %>

  <div class="mt">
    <label for="for_user">For user</label><br>
    <select class="mt" id="for_user" name="user_comment[for_user_id]">
      <option disabled>--- Please select a user ---</option>
      <%@users.each do |user|%>
        <option <%= (user.id.to_s == params[:id].to_s ) ? "selected" : ""%> value="<%= user.id %>"><%= user.email%></option>
      <%end%>
    </select>
  </div>

    <div class="mt">
      <label for="comment_body">Body</label><br>
      <textarea class="mt" id="comment_body" name="user_comment[body]"></textarea>
    </div>
  <input class="btn mt font-em" type="submit" value="Add User Comment">
</form>

Rails/Testing with Rails/SocialGoalsApp/app/views/users/show.html.erb
<h2 class="underline">Profile of <span><%= @user.email %><span></h2>

<h2 class="sm-padding-top">Goals</h2>
<ul class="goals">
  <% @goals.each do |goal| %>
    <a class="full" href="<%= goal_url(goal.id) %>">
      <li>
        <%= goal.is_public ? star : priv_star %><span class="steelblue"><%= goal.is_public ? "Public" : "Private" %></span> - <%= goal.title %>
        <div class="fr date"><%= goal.created_at.strftime("%a %H:%M")%></div>
      </li>
    </a>
  <% end %>
</ul>

<h2>Profile Comments</h2>
<ul class="comments">
  <% @user_comments.each do |user_comment| %>
    <li class="relative">
    &#x1F464;&nbsp;&nbsp;&nbsp;&nbsp;
      <span class="steelblue"><%= user_comment.author.email %></span> -
      <div class="fr date mr"><%= user_comment.created_at.strftime("%a %H:%M")%></div>
      <%= user_comment.body %>
      <% if user_comment.author == current_user %>
        <form class="delete-form" action="<%= user_comment_url(user_comment.id) %>" method="POST">
          <input type="hidden" name="_method" value="DELETE">
          <%= auth_token %>
          <input type="hidden" value="delete" name="_method" />
          <input class="delete-btn" type="submit" value="Delete comment" />
        </form>
      <% end %>
    </li>
  <% end %>
</ul>


<% if logged_in? %>
  <div class="pt mb">
    <a class="link" href="<%= new_goal_url %>">New goal</a>
    <a class="link" href="<%= user_comment_user_url(@user.id) %>">Comment on user</a>
  </div>
<% end %>